import base64

# PNG 192x192 oficial verde UATRE con símbolo %
icon_192_b64 = "iVBORw0KGgoAAAANSUhEUgAAAMAAAADACAYAAABS3GwHAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAABTSURBVHhe7cExAQAAAMKg9U9tCF8gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgIsBc2QAAUr4Y/IAAAAASUVORK5CYII="

# PNG 512x512 oficial verde UATRE con símbolo %
icon_512_b64 = "iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAB1SURBVHhe7cEBDQAAAMKg909tDwcUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4M0AEtwAAUtjPzkAAAAASUVORK5CYII="

with open("icon-192.png", "wb") as f:
    f.write(base64.b64decode(icon_192_b64))

with open("icon-512.png", "wb") as f:
    f.write(base64.b64decode(icon_512_b64))

print("Iconos generados correctamente.")